GET http://localhost:8080/api/users
Accept: application/json

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Vasya"
}

###

DELETE http://localhost:8080/api/users/5
Content-Type: application/json

###

GET http://localhost:8080/api/issues
Accept: application/json

###

POST http://localhost:8080/api/issues
Content-Type: application/json

{}

###

GET http://localhost:8080/api/repos
Accept: application/json

###

POST http://localhost:8080/api/repos
Content-Type: application/json

{
  "name": "todo-repo-check-check",
  "userId": 1
}

###

DELETE http://localhost:8080/api/repos/12
Accept: application/json

###

GET http://localhost:8080/api/teams
Accept: application/json

###

POST http://localhost:8080/api/teams
Content-Type: application/json

{
  "userId": 3,
  "repoId": 10
}

###

GET http://localhost:8080/api/issues
Accept: application/json

###

POST http://localhost:8080/api/issues
Content-Type: application/json

{
  "id": 9,
  "repoId": 11,
  "name": "First Issue",
  "description": "First Description",
  "tags": [
    "bug",
    "normal"
  ],
  "ownerId": 6,
  "assignmentId": 3
}

###

GET http://localhost:8080/api/issues/?param=Desc
Accept: application/json

###

DELETE http://localhost:8080/api/issues/8
Content-Type: application/json

###

